export function buildGenerateConnectionsPrompt(opts: {
  newWords: string[];
  oldWords: string[];
}) {
  return [
    `你是一位日文教學設計師。下面是使用者「今日新學」與「之前學過」的單字。`,
    `請找出新詞與舊詞之間的關係，並寫出能同時用到雙方的混合例句。`,
    ``,
    `關係類型 relationship_type 限用：`,
    `- same_topic（同主題）`,
    `- opposite（相反）`,
    `- similar（近義）`,
    `- often_together（常一起使用）`,
    `- same_kanji（共用漢字）`,
    `- same_radical（同部首）`,
    `- same_grammar（同文法 / 同助詞 pattern）`,
    `- confusing_pair（易混淆）`,
    `- same_situation（同場景）`,
    ``,
    `回傳嚴格 JSON：`,
    `{`,
    `  "relationships": [`,
    `    {`,
    `      "source_japanese": "今日新詞",`,
    `      "target_japanese": "舊詞",`,
    `      "relationship_type": "...",`,
    `      "explanation": "繁中簡短說明",`,
    `      "example_sentence": "包含雙方的日文例句"`,
    `    }`,
    `  ],`,
    `  "mixed_sentences": [`,
    `    {`,
    `      "japanese": "...",`,
    `      "romaji": "...",`,
    `      "meaning_zh": "繁中翻譯"`,
    `    }`,
    `  ]`,
    `}`,
    ``,
    `relationships 最多 12 條，mixed_sentences 最多 5 句。優先選擇真正自然有關連的配對；找不到也可以略過。不要 markdown 圍欄。`,
    ``,
    `今日新詞：${JSON.stringify(opts.newWords)}`,
    `之前學過：${JSON.stringify(opts.oldWords)}`,
  ].join("\n");
}
